# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/AES_wiring.bd
# Block Designs: The module: 'AES_wiring' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlconcat_0_0/AES_wiring_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlconcat_0_0 || ORIG_REF_NAME==AES_wiring_xlconcat_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_0/AES_wiring_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_0 || ORIG_REF_NAME==AES_wiring_xlslice_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_1/AES_wiring_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_1 || ORIG_REF_NAME==AES_wiring_xlslice_0_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_1_0/AES_wiring_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_1_0 || ORIG_REF_NAME==AES_wiring_xlslice_1_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_2_0/AES_wiring_xlslice_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_2_0 || ORIG_REF_NAME==AES_wiring_xlslice_2_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_2/AES_wiring_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_2 || ORIG_REF_NAME==AES_wiring_xlslice_0_2} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_0/AES_wiring_xlslice_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_0 || ORIG_REF_NAME==AES_wiring_xlslice_4_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_1/AES_wiring_xlslice_4_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_1 || ORIG_REF_NAME==AES_wiring_xlslice_4_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_2/AES_wiring_xlslice_4_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_2 || ORIG_REF_NAME==AES_wiring_xlslice_4_2} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_3/AES_wiring_xlslice_4_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_3 || ORIG_REF_NAME==AES_wiring_xlslice_4_3} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_4/AES_wiring_xlslice_4_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_4 || ORIG_REF_NAME==AES_wiring_xlslice_4_4} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_5/AES_wiring_xlslice_4_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_5 || ORIG_REF_NAME==AES_wiring_xlslice_4_5} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_6/AES_wiring_xlslice_4_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_6 || ORIG_REF_NAME==AES_wiring_xlslice_4_6} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_7/AES_wiring_xlslice_4_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_7 || ORIG_REF_NAME==AES_wiring_xlslice_4_7} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_8/AES_wiring_xlslice_4_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_8 || ORIG_REF_NAME==AES_wiring_xlslice_4_8} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_9/AES_wiring_xlslice_4_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_9 || ORIG_REF_NAME==AES_wiring_xlslice_4_9} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_10/AES_wiring_xlslice_4_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_10 || ORIG_REF_NAME==AES_wiring_xlslice_4_10} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_11/AES_wiring_xlslice_4_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_11 || ORIG_REF_NAME==AES_wiring_xlslice_4_11} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_12/AES_wiring_xlslice_4_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_12 || ORIG_REF_NAME==AES_wiring_xlslice_4_12} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_13/AES_wiring_xlslice_4_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_13 || ORIG_REF_NAME==AES_wiring_xlslice_4_13} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_14/AES_wiring_xlslice_4_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_14 || ORIG_REF_NAME==AES_wiring_xlslice_4_14} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_18_0/AES_wiring_xlslice_18_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_18_0 || ORIG_REF_NAME==AES_wiring_xlslice_18_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_20_0/AES_wiring_xlslice_20_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_20_0 || ORIG_REF_NAME==AES_wiring_xlslice_20_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_ShiftRowns_0_0/AES_wiring_ShiftRowns_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_ShiftRowns_0_0 || ORIG_REF_NAME==AES_wiring_ShiftRowns_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_MixColumns_0_0/AES_wiring_MixColumns_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_MixColumns_0_0 || ORIG_REF_NAME==AES_wiring_MixColumns_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SubBytes_0_0/AES_wiring_SubBytes_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SubBytes_0_0 || ORIG_REF_NAME==AES_wiring_SubBytes_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SevenSegCA_0_0/AES_wiring_SevenSegCA_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SevenSegCA_0_0 || ORIG_REF_NAME==AES_wiring_SevenSegCA_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SevenSegCA_1_0/AES_wiring_SevenSegCA_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SevenSegCA_1_0 || ORIG_REF_NAME==AES_wiring_SevenSegCA_1_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_inputs_0_0/AES_wiring_inputs_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_inputs_0_0 || ORIG_REF_NAME==AES_wiring_inputs_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux4_0_0/AES_wiring_mux4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux4_0_0 || ORIG_REF_NAME==AES_wiring_mux4_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_Display_Manager_0_0/AES_wiring_Display_Manager_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_Display_Manager_0_0 || ORIG_REF_NAME==AES_wiring_Display_Manager_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_AddRoundKey_0_0/AES_wiring_AddRoundKey_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_AddRoundKey_0_0 || ORIG_REF_NAME==AES_wiring_AddRoundKey_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux_0_0/AES_wiring_mux_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux_0_0 || ORIG_REF_NAME==AES_wiring_mux_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux_0_1/AES_wiring_mux_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux_0_1 || ORIG_REF_NAME==AES_wiring_mux_0_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_StateMachine_AES_0_0/AES_wiring_StateMachine_AES_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_StateMachine_AES_0_0 || ORIG_REF_NAME==AES_wiring_StateMachine_AES_0_0} -quiet] -quiet

# XDC: d:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.gen/sources_1/bd/AES_wiring/AES_wiring_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_wiring'. Do not add the DONT_TOUCH constraint.

# Block Designs: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/AES_wiring.bd
# Block Designs: The module: 'AES_wiring' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlconcat_0_0/AES_wiring_xlconcat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlconcat_0_0 || ORIG_REF_NAME==AES_wiring_xlconcat_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_0/AES_wiring_xlslice_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_0 || ORIG_REF_NAME==AES_wiring_xlslice_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_1/AES_wiring_xlslice_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_1 || ORIG_REF_NAME==AES_wiring_xlslice_0_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_1_0/AES_wiring_xlslice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_1_0 || ORIG_REF_NAME==AES_wiring_xlslice_1_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_2_0/AES_wiring_xlslice_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_2_0 || ORIG_REF_NAME==AES_wiring_xlslice_2_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_0_2/AES_wiring_xlslice_0_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_0_2 || ORIG_REF_NAME==AES_wiring_xlslice_0_2} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_0/AES_wiring_xlslice_4_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_0 || ORIG_REF_NAME==AES_wiring_xlslice_4_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_1/AES_wiring_xlslice_4_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_1 || ORIG_REF_NAME==AES_wiring_xlslice_4_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_2/AES_wiring_xlslice_4_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_2 || ORIG_REF_NAME==AES_wiring_xlslice_4_2} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_3/AES_wiring_xlslice_4_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_3 || ORIG_REF_NAME==AES_wiring_xlslice_4_3} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_4/AES_wiring_xlslice_4_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_4 || ORIG_REF_NAME==AES_wiring_xlslice_4_4} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_5/AES_wiring_xlslice_4_5.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_5 || ORIG_REF_NAME==AES_wiring_xlslice_4_5} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_6/AES_wiring_xlslice_4_6.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_6 || ORIG_REF_NAME==AES_wiring_xlslice_4_6} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_7/AES_wiring_xlslice_4_7.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_7 || ORIG_REF_NAME==AES_wiring_xlslice_4_7} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_8/AES_wiring_xlslice_4_8.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_8 || ORIG_REF_NAME==AES_wiring_xlslice_4_8} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_9/AES_wiring_xlslice_4_9.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_9 || ORIG_REF_NAME==AES_wiring_xlslice_4_9} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_10/AES_wiring_xlslice_4_10.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_10 || ORIG_REF_NAME==AES_wiring_xlslice_4_10} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_11/AES_wiring_xlslice_4_11.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_11 || ORIG_REF_NAME==AES_wiring_xlslice_4_11} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_12/AES_wiring_xlslice_4_12.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_12 || ORIG_REF_NAME==AES_wiring_xlslice_4_12} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_13/AES_wiring_xlslice_4_13.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_13 || ORIG_REF_NAME==AES_wiring_xlslice_4_13} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_4_14/AES_wiring_xlslice_4_14.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_4_14 || ORIG_REF_NAME==AES_wiring_xlslice_4_14} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_18_0/AES_wiring_xlslice_18_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_18_0 || ORIG_REF_NAME==AES_wiring_xlslice_18_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_xlslice_20_0/AES_wiring_xlslice_20_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_xlslice_20_0 || ORIG_REF_NAME==AES_wiring_xlslice_20_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_ShiftRowns_0_0/AES_wiring_ShiftRowns_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_ShiftRowns_0_0 || ORIG_REF_NAME==AES_wiring_ShiftRowns_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_MixColumns_0_0/AES_wiring_MixColumns_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_MixColumns_0_0 || ORIG_REF_NAME==AES_wiring_MixColumns_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SubBytes_0_0/AES_wiring_SubBytes_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SubBytes_0_0 || ORIG_REF_NAME==AES_wiring_SubBytes_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SevenSegCA_0_0/AES_wiring_SevenSegCA_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SevenSegCA_0_0 || ORIG_REF_NAME==AES_wiring_SevenSegCA_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_SevenSegCA_1_0/AES_wiring_SevenSegCA_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_SevenSegCA_1_0 || ORIG_REF_NAME==AES_wiring_SevenSegCA_1_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_inputs_0_0/AES_wiring_inputs_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_inputs_0_0 || ORIG_REF_NAME==AES_wiring_inputs_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux4_0_0/AES_wiring_mux4_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux4_0_0 || ORIG_REF_NAME==AES_wiring_mux4_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_Display_Manager_0_0/AES_wiring_Display_Manager_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_Display_Manager_0_0 || ORIG_REF_NAME==AES_wiring_Display_Manager_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_AddRoundKey_0_0/AES_wiring_AddRoundKey_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_AddRoundKey_0_0 || ORIG_REF_NAME==AES_wiring_AddRoundKey_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux_0_0/AES_wiring_mux_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux_0_0 || ORIG_REF_NAME==AES_wiring_mux_0_0} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_mux_0_1/AES_wiring_mux_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_mux_0_1 || ORIG_REF_NAME==AES_wiring_mux_0_1} -quiet] -quiet

# IP: D:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.srcs/sources_1/bd/AES_wiring/ip/AES_wiring_StateMachine_AES_0_0/AES_wiring_StateMachine_AES_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES_wiring_StateMachine_AES_0_0 || ORIG_REF_NAME==AES_wiring_StateMachine_AES_0_0} -quiet] -quiet

# XDC: d:/repos/AES_Encrypt_VHDL/AES_encryption/AES_encryption.gen/sources_1/bd/AES_wiring/AES_wiring_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES_wiring'. Do not add the DONT_TOUCH constraint.
